"""empty message

Revision ID: 8f16aff16e84
Revises: 
Create Date: 2019-06-08 17:54:39.356350

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = "8f16aff16e84"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "language",
        sa.Column("id", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_key", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text_key", "group_id", name="unique_text_key_group_id"),
    )
    op.create_table(
        "translated_text",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["language"], ["language.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "language", name="unique_key_language"),
    )
    # ### end Alembic commands ###
    data_upgrade()


def data_upgrade():
    now = datetime.utcnow()
    language_table = table(
        "language", column("id", sa.String), column("created_at", sa.DateTime)
    )
    op.bulk_insert(
        language_table, [{"id": "sv", "created_at": now}, {"id": "en", "created_at": now}]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translated_text")
    op.drop_table("text_group")
    op.drop_table("language")
    op.drop_table("group")
    # ### end Alembic commands ###
